### ISSUE TITLE
Issue-first commit

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/4snap#2]
Automated Review Comments
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
Issues in packages/app/.eslintrc.json:
  - (3, 'Hardcoded string found')
Issues in packages/app/components/Image.tsx:
  - (3, 'Hardcoded string found')
Issues in packages/app/components/Layout/index.tsx:
  - (2, 'Hardcoded string found')
Issues in packages/app/components/Layout/mainDashboard.tsx:
  - (2, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
Issues in packages/app/components/Loader/index.tsx:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
Issues in packages/app/components/Modal/index.tsx:
  - (3, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Line exceeds 80 characters')
  - (133, 'Hardcoded string found')
Issues in packages/app/components/Navbar/navbar.tsx:
  - (2, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
Issues in packages/app/components/Navbar/sidebar.tsx:
  - (12, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
  - (64, 'Line exceeds 80 characters')
  - (73, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (85, 'Hardcoded string found')
  - (86, 'Line exceeds 80 characters')
Issues in packages/app/components/Navbar/topbar.tsx:
  - (4, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (86, 'Line exceeds 80 characters')
  - (86, 'Hardcoded string found')
  - (92, 'Line exceeds 80 characters')
  - (98, 'Line exceeds 80 characters')
  - (102, 'Line exceeds 80 characters')
  - (104, 'Line exceeds 80 characters')
Issues in packages/app/config/index.ts:
  - (9, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
Issues in packages/app/http/axios.ts:
  - (3, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
Issues in packages/app/http/index.ts:
  - (2, 'Hardcoded string found')
Issues in packages/app/next-env.d.ts:
  - (2, 'Hardcoded string found')
Issues in packages/app/next.config.js:
  - (2, 'Hardcoded string found')
Issues in packages/app/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
Issues in packages/app/pages/_document.tsx:
  - (6, 'Hardcoded string found')
Issues in packages/app/pages/api/config/env.ts:
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in packages/app/pages/api/config/mongodb.ts:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in packages/app/pages/api/controller/user.ts:
  - (2, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
Issues in packages/app/pages/api/error/catchErrors.ts:
  - (2, 'Hardcoded string found')
Issues in packages/app/pages/api/hello.ts:
  - (3, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
Issues in packages/app/pages/api/helper/sendResponse.ts:
  - (2, 'Hardcoded string found')
Issues in packages/app/pages/api/middlewares/error.ts:
  - (2, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
