### ISSUE TITLE
Issue-started auth

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/4snap#4]
Automated Review Comments
Issues in packages/app/package.json:
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in packages/app/pages/api/config/env.ts:
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
Issues in packages/app/pages/auth/index.tsx:
  - (3, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
Issues in yarn.lock:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (73, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (76, 'Hardcoded string found')
  - (89, 'Line exceeds 80 characters')
  - (90, 'Line exceeds 80 characters')
  - (92, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (100, 'Line exceeds 80 characters')
  - (101, 'Line exceeds 80 characters')
  - (108, 'Line exceeds 80 characters')
  - (109, 'Line exceeds 80 characters')
  - (115, 'Line exceeds 80 characters')
  - (117, 'Line exceeds 80 characters')
  - (118, 'Line exceeds 80 characters')
  - (122, 'Line exceeds 80 characters')
  - (123, 'Line exceeds 80 characters')
  - (127, 'Line exceeds 80 characters')
  - (129, 'Line exceeds 80 characters')
  - (130, 'Line exceeds 80 characters')
  - (134, 'Line exceeds 80 characters')
  - (135, 'Line exceeds 80 characters')
  - (139, 'Line exceeds 80 characters')
  - (141, 'Line exceeds 80 characters')
  - (142, 'Line exceeds 80 characters')
  - (146, 'Line exceeds 80 characters')
  - (147, 'Line exceeds 80 characters')
  - (151, 'Line exceeds 80 characters')
  - (152, 'Line exceeds 80 characters')
  - (154, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (159, 'Line exceeds 80 characters')
  - (161, 'Hardcoded string found')
  - (166, 'Line exceeds 80 characters')
  - (167, 'Line exceeds 80 characters')
  - (169, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (176, 'Line exceeds 80 characters')
  - (177, 'Line exceeds 80 characters')
  - (179, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (184, 'Line exceeds 80 characters')
  - (185, 'Line exceeds 80 characters')
  - (187, 'Hardcoded string found')
  - (188, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
  - (192, 'Hardcoded string found')
  - (200, 'Line exceeds 80 characters')
  - (201, 'Line exceeds 80 characters')
  - (203, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (208, 'Line exceeds 80 characters')
  - (209, 'Line exceeds 80 characters')
  - (213, 'Line exceeds 80 characters')
  - (214, 'Line exceeds 80 characters')
  - (216, 'Hardcoded string found')
  - (217, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (224, 'Line exceeds 80 characters')
  - (225, 'Line exceeds 80 characters')
  - (227, 'Hardcoded string found')
  - (231, 'Line exceeds 80 characters')
  - (232, 'Line exceeds 80 characters')
  - (234, 'Hardcoded string found')
  - (235, 'Hardcoded string found')
  - (239, 'Line exceeds 80 characters')
  - (240, 'Line exceeds 80 characters')
  - (242, 'Hardcoded string found')
  - (243, 'Hardcoded string found')
  - (248, 'Line exceeds 80 characters')
  - (249, 'Line exceeds 80 characters')
  - (251, 'Hardcoded string found')
  - (252, 'Hardcoded string found')
  - (256, 'Line exceeds 80 characters')
  - (257, 'Line exceeds 80 characters')
  - (261, 'Line exceeds 80 characters')
  - (263, 'Line exceeds 80 characters')
  - (264, 'Line exceeds 80 characters')
  - (268, 'Line exceeds 80 characters')
  - (269, 'Line exceeds 80 characters')
  - (275, 'Line exceeds 80 characters')
  - (282, 'Line exceeds 80 characters')
  - (283, 'Line exceeds 80 characters')
  - (287, 'Line exceeds 80 characters')
  - (289, 'Line exceeds 80 characters')
  - (290, 'Line exceeds 80 characters')
  - (295, 'Line exceeds 80 characters')
  - (296, 'Line exceeds 80 characters')
  - (298, 'Line exceeds 80 characters')
  - (299, 'Line exceeds 80 characters')
  - (303, 'Line exceeds 80 characters')
  - (304, 'Line exceeds 80 characters')
  - (309, 'Line exceeds 80 characters')
  - (310, 'Line exceeds 80 characters')
  - (315, 'Line exceeds 80 characters')
  - (316, 'Line exceeds 80 characters')
  - (322, 'Line exceeds 80 characters')
  - (323, 'Line exceeds 80 characters')
  - (329, 'Line exceeds 80 characters')
  - (331, 'Line exceeds 80 characters')
  - (332, 'Line exceeds 80 characters')
  - (336, 'Line exceeds 80 characters')
  - (337, 'Line exceeds 80 characters')
  - (341, 'Line exceeds 80 characters')
  - (349, 'Line exceeds 80 characters')
  - (350, 'Line exceeds 80 characters')
  - (352, 'Line exceeds 80 characters')
  - (353, 'Line exceeds 80 characters')
  - (357, 'Line exceeds 80 characters')
  - (358, 'Line exceeds 80 characters')
  - (362, 'Line exceeds 80 characters')
  - (369, 'Line exceeds 80 characters')
  - (370, 'Line exceeds 80 characters')
  - (374, 'Line exceeds 80 characters')
  - (375, 'Line exceeds 80 characters')
  - (381, 'Line exceeds 80 characters')
  - (382, 'Line exceeds 80 characters')
  - (386, 'Line exceeds 80 characters')
  - (388, 'Hardcoded string found')
  - (389, 'Hardcoded string found')
  - (393, 'Line exceeds 80 characters')
  - (394, 'Line exceeds 80 characters')
  - (398, 'Line exceeds 80 characters')
  - (399, 'Line exceeds 80 characters')
  - (403, 'Line exceeds 80 characters')
  - (405, 'Line exceeds 80 characters')
  - (406, 'Line exceeds 80 characters')
  - (410, 'Line exceeds 80 characters')
  - (411, 'Line exceeds 80 characters')
  - (415, 'Line exceeds 80 characters')
  - (422, 'Line exceeds 80 characters')
  - (423, 'Line exceeds 80 characters')
  - (425, 'Hardcoded string found')
  - (429, 'Line exceeds 80 characters')
  - (431, 'Hardcoded string found')
  - (436, 'Line exceeds 80 characters')
  - (437, 'Line exceeds 80 characters')
  - (441, 'Line exceeds 80 characters')
  - (443, 'Line exceeds 80 characters')
  - (444, 'Line exceeds 80 characters')
  - (448, 'Line exceeds 80 characters')
  - (449, 'Line exceeds 80 characters')
  - (451, 'Hardcoded string found')
  - (456, 'Line exceeds 80 characters')
  - (457, 'Line exceeds 80 characters')
  - (467, 'Line exceeds 80 characters')
  - (468, 'Line exceeds 80 characters')
  - (480, 'Line exceeds 80 characters')
  - (481, 'Line exceeds 80 characters')
  - (485, 'Line exceeds 80 characters')
  - (486, 'Line exceeds 80 characters')
  - (492, 'Line exceeds 80 characters')
  - (493, 'Line exceeds 80 characters')
  - (498, 'Line exceeds 80 characters')
  - (499, 'Line exceeds 80 characters')
  - (507, 'Line exceeds 80 characters')
  - (508, 'Line exceeds 80 characters')
  - (510, 'Line exceeds 80 characters')
  - (511, 'Line exceeds 80 characters')
  - (515, 'Line exceeds 80 characters')
  - (516, 'Line exceeds 80 characters')
  - (520, 'Line exceeds 80 characters')
  - (522, 'Line exceeds 80 characters')
  - (523, 'Line exceeds 80 characters')
  - (528, 'Line exceeds 80 characters')
  - (529, 'Line exceeds 80 characters')
  - (536, 'Line exceeds 80 characters')
  - (537, 'Line exceeds 80 characters')
  - (543, 'Line exceeds 80 characters')
  - (550, 'Line exceeds 80 characters')
  - (551, 'Line exceeds 80 characters')
  - (557, 'Line exceeds 80 characters')
  - (564, 'Line exceeds 80 characters')
  - (565, 'Line exceeds 80 characters')
  - (569, 'Line exceeds 80 characters')
  - (571, 'Line exceeds 80 characters')
  - (572, 'Line exceeds 80 characters')
  - (576, 'Line exceeds 80 characters')
  - (577, 'Line exceeds 80 characters')
  - (581, 'Line exceeds 80 characters')
  - (582, 'Line exceeds 80 characters')
  - (589, 'Line exceeds 80 characters')
  - (590, 'Line exceeds 80 characters')
  - (594, 'Line exceeds 80 characters')
  - (595, 'Line exceeds 80 characters')
  - (599, 'Line exceeds 80 characters')
  - (600, 'Line exceeds 80 characters')
  - (604, 'Line exceeds 80 characters')
  - (605, 'Line exceeds 80 characters')
  - (611, 'Line exceeds 80 characters')
  - (613, 'Line exceeds 80 characters')
  - (614, 'Line exceeds 80 characters')
  - (618, 'Line exceeds 80 characters')
  - (619, 'Line exceeds 80 characters')
  - (625, 'Line exceeds 80 characters')
  - (627, 'Line exceeds 80 characters')
  - (628, 'Line exceeds 80 characters')
  - (632, 'Line exceeds 80 characters')
  - (633, 'Line exceeds 80 characters')
  - (637, 'Line exceeds 80 characters')
  - (639, 'Line exceeds 80 characters')
  - (640, 'Line exceeds 80 characters')
  - (644, 'Line exceeds 80 characters')
  - (645, 'Line exceeds 80 characters')
  - (649, 'Line exceeds 80 characters')
  - (651, 'Line exceeds 80 characters')
  - (652, 'Line exceeds 80 characters')
  - (656, 'Line exceeds 80 characters')
  - (657, 'Line exceeds 80 characters')
  - (659, 'Hardcoded string found')
  - (660, 'Hardcoded string found')
  - (661, 'Hardcoded string found')
  - (662, 'Hardcoded string found')
  - (666, 'Line exceeds 80 characters')
  - (667, 'Line exceeds 80 characters')
  - (671, 'Line exceeds 80 characters')
  - (672, 'Line exceeds 80 characters')
  - (674, 'Hardcoded string found')
  - (675, 'Hardcoded string found')
  - (676, 'Hardcoded string found')
  - (677, 'Hardcoded string found')
  - (678, 'Hardcoded string found')
  - (682, 'Line exceeds 80 characters')
  - (683, 'Line exceeds 80 characters')
  - (687, 'Line exceeds 80 characters')
  - (688, 'Line exceeds 80 characters')
  - (695, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
