### ISSUE TITLE
Issue-added major changes

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/4snap#56]
Automated Review Comments
Issues in packages/app/pages/api/auth/cliAuth.ts:
  - (3, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in packages/app/pages/api/controller/cliAuth.ts:
  - (2, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
Issues in packages/cli/README.md:
  - (4, 'TODO found')
Issues in packages/cli/dist/commands/auth.js:
  - (5, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in packages/cli/dist/helpers/axios.js:
  - (2, 'Hardcoded string found')
Issues in packages/cli/dist/helpers/loader.js:
  - (2, 'Hardcoded string found')
Issues in packages/cli/dist/helpers/logger.js:
  - (2, 'Hardcoded string found')
Issues in packages/cli/dist/helpers/serverResponse.js:
  - (4, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in packages/cli/dist/index.js:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in packages/cli/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
Issues in packages/cli/src/commands/auth.ts:
  - (12, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in packages/cli/src/helpers/axios.ts:
  - (2, 'Hardcoded string found')
Issues in packages/cli/src/helpers/loader.ts:
  - (2, 'Hardcoded string found')
Issues in packages/cli/src/helpers/logger.ts:
  - (2, 'Hardcoded string found')
Issues in packages/cli/src/helpers/serverResponse.ts:
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
Issues in packages/cli/src/index.ts:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in packages/cli/tsconfig.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
Issues in yarn.lock:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
  - (59, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')
  - (83, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (88, 'Line exceeds 80 characters')
  - (89, 'Line exceeds 80 characters')
  - (91, 'Hardcoded string found')
  - (95, 'Line exceeds 80 characters')
  - (102, 'Line exceeds 80 characters')
  - (103, 'Line exceeds 80 characters')
  - (109, 'Line exceeds 80 characters')
  - (110, 'Line exceeds 80 characters')
  - (114, 'Line exceeds 80 characters')
  - (115, 'Line exceeds 80 characters')
  - (119, 'Line exceeds 80 characters')
  - (120, 'Line exceeds 80 characters')
  - (127, 'Line exceeds 80 characters')
  - (128, 'Line exceeds 80 characters')
  - (130, 'Line exceeds 80 characters')
  - (131, 'Line exceeds 80 characters')
  - (135, 'Line exceeds 80 characters')
  - (136, 'Line exceeds 80 characters')
  - (143, 'Line exceeds 80 characters')
  - (144, 'Line exceeds 80 characters')
  - (151, 'Line exceeds 80 characters')
  - (152, 'Line exceeds 80 characters')
  - (158, 'Line exceeds 80 characters')
  - (160, 'Line exceeds 80 characters')
  - (161, 'Line exceeds 80 characters')
  - (165, 'Line exceeds 80 characters')
  - (166, 'Line exceeds 80 characters')
  - (170, 'Line exceeds 80 characters')
  - (172, 'Line exceeds 80 characters')
  - (173, 'Line exceeds 80 characters')
  - (177, 'Line exceeds 80 characters')
  - (178, 'Line exceeds 80 characters')
  - (186, 'Line exceeds 80 characters')
  - (187, 'Line exceeds 80 characters')
  - (195, 'Line exceeds 80 characters')
  - (197, 'Line exceeds 80 characters')
  - (198, 'Line exceeds 80 characters')
  - (202, 'Line exceeds 80 characters')
  - (203, 'Line exceeds 80 characters')
  - (210, 'Line exceeds 80 characters')
  - (211, 'Line exceeds 80 characters')
  - (218, 'Line exceeds 80 characters')
  - (226, 'Line exceeds 80 characters')
  - (227, 'Line exceeds 80 characters')
  - (234, 'Line exceeds 80 characters')
  - (235, 'Line exceeds 80 characters')
  - (239, 'Line exceeds 80 characters')
  - (240, 'Line exceeds 80 characters')
  - (244, 'Line exceeds 80 characters')
  - (251, 'Line exceeds 80 characters')
  - (252, 'Line exceeds 80 characters')
  - (258, 'Line exceeds 80 characters')
  - (259, 'Line exceeds 80 characters')
  - (265, 'Line exceeds 80 characters')
  - (266, 'Line exceeds 80 characters')
  - (270, 'Line exceeds 80 characters')
  - (271, 'Line exceeds 80 characters')
  - (275, 'Line exceeds 80 characters')
  - (276, 'Line exceeds 80 characters')
  - (280, 'Line exceeds 80 characters')
  - (281, 'Line exceeds 80 characters')
  - (285, 'Line exceeds 80 characters')
  - (292, 'Line exceeds 80 characters')
  - (293, 'Line exceeds 80 characters')
  - (297, 'Line exceeds 80 characters')
  - (304, 'Line exceeds 80 characters')
  - (305, 'Line exceeds 80 characters')
  - (311, 'Line exceeds 80 characters')
  - (313, 'Line exceeds 80 characters')
  - (314, 'Line exceeds 80 characters')
  - (318, 'Line exceeds 80 characters')
  - (319, 'Line exceeds 80 characters')
  - (323, 'Line exceeds 80 characters')
  - (325, 'Line exceeds 80 characters')
  - (326, 'Line exceeds 80 characters')
  - (330, 'Line exceeds 80 characters')
  - (331, 'Line exceeds 80 characters')
  - (335, 'Line exceeds 80 characters')
  - (342, 'Line exceeds 80 characters')
  - (343, 'Line exceeds 80 characters')
  - (351, 'Line exceeds 80 characters')
  - (358, 'Line exceeds 80 characters')
  - (359, 'Line exceeds 80 characters')
  - (366, 'Line exceeds 80 characters')
  - (373, 'Line exceeds 80 characters')
  - (374, 'Line exceeds 80 characters')
  - (382, 'Line exceeds 80 characters')
  - (390, 'Line exceeds 80 characters')
  - (391, 'Line exceeds 80 characters')
  - (399, 'Line exceeds 80 characters')
  - (400, 'Line exceeds 80 characters')
  - (402, 'Line exceeds 80 characters')
  - (403, 'Line exceeds 80 characters')
  - (407, 'Line exceeds 80 characters')
  - (408, 'Line exceeds 80 characters')
  - (414, 'Line exceeds 80 characters')
  - (415, 'Line exceeds 80 characters')
  - (419, 'Line exceeds 80 characters')
  - (427, 'Line exceeds 80 characters')
  - (428, 'Line exceeds 80 characters')
  - (432, 'Line exceeds 80 characters')
  - (433, 'Line exceeds 80 characters')
  - (453, 'Line exceeds 80 characters')
  - (460, 'Line exceeds 80 characters')
  - (461, 'Line exceeds 80 characters')
  - (465, 'Line exceeds 80 characters')
  - (467, 'Line exceeds 80 characters')
  - (468, 'Line exceeds 80 characters')
  - (472, 'Line exceeds 80 characters')
  - (473, 'Line exceeds 80 characters')
  - (477, 'Line exceeds 80 characters')
  - (484, 'Line exceeds 80 characters')
  - (485, 'Line exceeds 80 characters')
  - (489, 'Line exceeds 80 characters')
  - (490, 'Line exceeds 80 characters')
  - (494, 'Line exceeds 80 characters')
  - (501, 'Line exceeds 80 characters')
  - (502, 'Line exceeds 80 characters')
  - (504, 'Line exceeds 80 characters')
  - (506, 'Line exceeds 80 characters')
  - (507, 'Line exceeds 80 characters')
  - (511, 'Line exceeds 80 characters')
  - (518, 'Line exceeds 80 characters')
  - (519, 'Line exceeds 80 characters')
  - (527, 'Line exceeds 80 characters')
  - (529, 'Line exceeds 80 characters')
  - (530, 'Line exceeds 80 characters')
  - (534, 'Line exceeds 80 characters')
  - (535, 'Line exceeds 80 characters')
  - (542, 'Line exceeds 80 characters')
  - (543, 'Line exceeds 80 characters')
  - (550, 'Line exceeds 80 characters')
  - (552, 'Line exceeds 80 characters')
  - (553, 'Line exceeds 80 characters')
  - (557, 'Line exceeds 80 characters')
  - (558, 'Line exceeds 80 characters')
  - (562, 'Line exceeds 80 characters')
  - (570, 'Line exceeds 80 characters')
  - (571, 'Line exceeds 80 characters')
  - (578, 'Line exceeds 80 characters')
  - (579, 'Line exceeds 80 characters')
  - (593, 'Line exceeds 80 characters')
  - (594, 'Line exceeds 80 characters')
  - (608, 'Line exceeds 80 characters')
  - (609, 'Line exceeds 80 characters')
  - (613, 'Line exceeds 80 characters')
  - (620, 'Line exceeds 80 characters')
  - (621, 'Line exceeds 80 characters')
  - (629, 'Line exceeds 80 characters')
  - (630, 'Line exceeds 80 characters')
  - (636, 'Line exceeds 80 characters')
  - (637, 'Line exceeds 80 characters')
  - (643, 'Line exceeds 80 characters')
  - (645, 'Line exceeds 80 characters')
  - (646, 'Line exceeds 80 characters')
  - (649, 'Line exceeds 80 characters')
  - (651, 'Line exceeds 80 characters')
  - (652, 'Line exceeds 80 characters')
  - (659, 'Line exceeds 80 characters')
  - (660, 'Line exceeds 80 characters')
  - (667, 'Line exceeds 80 characters')
  - (668, 'Line exceeds 80 characters')
  - (675, 'Line exceeds 80 characters')
  - (682, 'Line exceeds 80 characters')
  - (683, 'Line exceeds 80 characters')
  - (687, 'Line exceeds 80 characters')
  - (688, 'Line exceeds 80 characters')
  - (695, 'Line exceeds 80 characters')
  - (696, 'Line exceeds 80 characters')
  - (702, 'Line exceeds 80 characters')
  - (703, 'Line exceeds 80 characters')
  - (710, 'Line exceeds 80 characters')
  - (711, 'Line exceeds 80 characters')
  - (715, 'Line exceeds 80 characters')
  - (717, 'Line exceeds 80 characters')
  - (718, 'Line exceeds 80 characters')
  - (722, 'Line exceeds 80 characters')
  - (723, 'Line exceeds 80 characters')
  - (731, 'Line exceeds 80 characters')
  - (733, 'Line exceeds 80 characters')
  - (734, 'Line exceeds 80 characters')
  - (739, 'Line exceeds 80 characters')
  - (740, 'Line exceeds 80 characters')
  - (744, 'Line exceeds 80 characters')
  - (745, 'Line exceeds 80 characters')
  - (749, 'Line exceeds 80 characters')
  - (751, 'Line exceeds 80 characters')
  - (752, 'Line exceeds 80 characters')
  - (756, 'Line exceeds 80 characters')
  - (757, 'Line exceeds 80 characters')
  - (761, 'Line exceeds 80 characters')
  - (768, 'Line exceeds 80 characters')
  - (769, 'Line exceeds 80 characters')
  - (775, 'Line exceeds 80 characters')
  - (776, 'Line exceeds 80 characters')
  - (784, 'Line exceeds 80 characters')
  - (792, 'Line exceeds 80 characters')
  - (793, 'Line exceeds 80 characters')
  - (799, 'Line exceeds 80 characters')
  - (800, 'Line exceeds 80 characters')
  - (806, 'Line exceeds 80 characters')
  - (807, 'Line exceeds 80 characters')
  - (813, 'Line exceeds 80 characters')
  - (820, 'Line exceeds 80 characters')
  - (821, 'Line exceeds 80 characters')
  - (825, 'Line exceeds 80 characters')
  - (827, 'Line exceeds 80 characters')
  - (828, 'Line exceeds 80 characters')
  - (832, 'Line exceeds 80 characters')
  - (833, 'Line exceeds 80 characters')
  - (839, 'Line exceeds 80 characters')
  - (841, 'Line exceeds 80 characters')
  - (842, 'Line exceeds 80 characters')
  - (846, 'Line exceeds 80 characters')
  - (847, 'Line exceeds 80 characters')
  - (851, 'Line exceeds 80 characters')
  - (853, 'Line exceeds 80 characters')
  - (854, 'Line exceeds 80 characters')
  - (858, 'Line exceeds 80 characters')
  - (859, 'Line exceeds 80 characters')
  - (863, 'Line exceeds 80 characters')
  - (870, 'Line exceeds 80 characters')
  - (871, 'Line exceeds 80 characters')
  - (875, 'Line exceeds 80 characters')
  - (883, 'Line exceeds 80 characters')
  - (884, 'Line exceeds 80 characters')
  - (886, 'Hardcoded string found')
  - (887, 'Hardcoded string found')
  - (891, 'Line exceeds 80 characters')
  - (892, 'Line exceeds 80 characters')
  - (898, 'Line exceeds 80 characters')
  - (900, 'Line exceeds 80 characters')
  - (901, 'Line exceeds 80 characters')
  - (905, 'Line exceeds 80 characters')
  - (906, 'Line exceeds 80 characters')
  - (914, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
