### ISSUE TITLE
Issue-added major changes

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/4snap#6]
Automated Review Comments
Issues in packages/app/config/index.ts:
  - (8, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
Issues in packages/app/hooks/useIsReady.ts:
  - (2, 'Hardcoded string found')
Issues in packages/app/pages/_app.tsx:
  - (9, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in packages/app/pages/api/command/cli/create.ts:
  - (3, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in packages/app/pages/api/command/cli/get.ts:
  - (3, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in packages/app/pages/api/command/inApp/create.ts:
  - (3, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in packages/app/pages/api/command/inApp/get.ts:
  - (3, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in packages/app/pages/api/config/env.ts:
  - (8, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in packages/app/pages/api/config/mongodb.ts:
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in packages/app/pages/api/controller/commands.ts:
  - (2, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
Issues in packages/app/pages/api/controller/user.ts:
  - (2, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
Issues in packages/app/pages/api/helper/validator.ts:
  - (2, 'Hardcoded string found')
Issues in packages/app/pages/api/middlewares/auth.ts:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
Issues in packages/app/pages/api/model/index.ts:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
Issues in packages/app/pages/api/user/create.ts:
  - (4, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in packages/app/pages/api/user/getInfo.ts:
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
Issues in packages/app/pages/commands/index.tsx:
  - (13, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (83, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (95, 'Line exceeds 80 characters')
  - (101, 'Line exceeds 80 characters')
  - (149, 'Line exceeds 80 characters')
  - (151, 'Line exceeds 80 characters')
  - (154, 'Line exceeds 80 characters')
  - (156, 'Hardcoded string found')
  - (163, 'Line exceeds 80 characters')
  - (169, 'Line exceeds 80 characters')
  - (183, 'Line exceeds 80 characters')
Issues in packages/app/pages/dashboard/index.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
Issues in packages/app/util/index.ts:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in packages/app/util/response.ts:
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
Issues in packages/app/util/serverPassageAuth.ts:
  - (9, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
