### ISSUE TITLE
Issue-added fetching of commands

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/4snap#86]
Automated Review Comments
Issues in packages/app/pages/api/command/cli/create.ts:
  - (3, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
Issues in packages/app/pages/api/command/cli/get.ts:
  - (3, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
Issues in packages/cli/dist/commands/createCmd.js:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (64, 'Hardcoded string found')
Issues in packages/cli/dist/commands/listCmds.js:
  - (4, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in packages/cli/dist/helpers/axios.js:
  - (2, 'Hardcoded string found')
Issues in packages/cli/dist/index.js:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
Issues in packages/cli/src/commands/createCmd.ts:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (80, 'Hardcoded string found')
Issues in packages/cli/src/commands/listCmds.ts:
  - (4, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
Issues in packages/cli/src/helpers/axios.ts:
  - (2, 'Hardcoded string found')
Issues in packages/cli/src/index.ts:
  - (2, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
