### ISSUE TITLE
Issue-removed build folder

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/4snap#88]
Automated Review Comments
Issues in packages/cli/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
Issues in packages/cli/src/commands/auth.ts:
  - (4, 'Hardcoded string found')
Issues in packages/cli/src/config/index.ts:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in packages/cli/src/index.ts:
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
